// <auto-generated />
using System;
using ClbTinhoc.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClbTinhoc.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250509093129_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClbTinhoc.Web.Models.DiemThi", b =>
                {
                    b.Property<int>("MaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiem"));

                    b.Property<float>("Diem")
                        .HasColumnType("real");

                    b.Property<int>("LanThi")
                        .HasColumnType("int");

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaDiem");

                    b.HasIndex("MaKhoaHoc");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("diemthi", (string)null);
                });

            modelBuilder.Entity("ClbTinhoc.Web.Models.KetQua", b =>
                {
                    b.Property<int>("MaKetQua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKetQua"));

                    b.Property<float>("DiemCuoiKy")
                        .HasColumnType("real");

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int");

                    b.Property<string>("MaSinhVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.HasKey("MaKetQua");

                    b.HasIndex("MaKhoaHoc");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("ketqua", (string)null);
                });

            modelBuilder.Entity("ClbTinhoc.Web.Models.KhoaHoc", b =>
                {
                    b.Property<int>("MaKhoaHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoaHoc"));

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhoaHoc");

                    b.ToTable("khoahoc", (string)null);
                });

            modelBuilder.Entity("ClbTinhoc.Web.Models.KhoaHoc_SinhVien", b =>
                {
                    b.Property<string>("MaSinhVien")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnOrder(0);

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("MaSinhVien", "MaKhoaHoc");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("student_khoahoc", (string)null);
                });

            modelBuilder.Entity("ClbTinhoc.Web.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSinhVien")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("MaSinhVien");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HoTen");

                    b.Property<string>("LopSinhHoat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LopSinhHoat");

                    b.Property<DateTime>("NgayThamGia")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayThamGia");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SoDienThoai");

                    b.HasKey("MaSinhVien");

                    b.ToTable("sinhvien", (string)null);
                });

            modelBuilder.Entity("ClbTinhoc.Web.Models.Support", b =>
                {
                    b.Property<string>("MaSupport")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LopSinhHoat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSupport");

                    b.ToTable("support", (string)null);
                });

            modelBuilder.Entity("ClbTinhoc.Web.Models.SupportKhoaHoc", b =>
                {
                    b.Property<string>("MaSupport")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(0);

                    b.Property<int>("MaKhoaHoc")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("MaSupport", "MaKhoaHoc");

                    b.HasIndex("MaKhoaHoc");

                    b.ToTable("support_khoahoc", (string)null);
                });

            modelBuilder.Entity("ClbTinhoc.Web.Models.UserLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("user_login", (string)null);
                });

            modelBuilder.Entity("ClbTinhoc.Web.Models.DiemThi", b =>
                {
                    b.HasOne("ClbTinhoc.Web.Models.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClbTinhoc.Web.Models.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("ClbTinhoc.Web.Models.KetQua", b =>
                {
                    b.HasOne("ClbTinhoc.Web.Models.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClbTinhoc.Web.Models.SinhVien", "SinhVien")
                        .WithMany()
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("ClbTinhoc.Web.Models.KhoaHoc_SinhVien", b =>
                {
                    b.HasOne("ClbTinhoc.Web.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("KhoaHoc_SinhVien")
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClbTinhoc.Web.Models.SinhVien", "SinhVien")
                        .WithMany("KhoaHoc_SinhVien")
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("ClbTinhoc.Web.Models.SupportKhoaHoc", b =>
                {
                    b.HasOne("ClbTinhoc.Web.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("SupportKhoaHoc")
                        .HasForeignKey("MaKhoaHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClbTinhoc.Web.Models.Support", "Support")
                        .WithMany()
                        .HasForeignKey("MaSupport")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaHoc");

                    b.Navigation("Support");
                });

            modelBuilder.Entity("ClbTinhoc.Web.Models.KhoaHoc", b =>
                {
                    b.Navigation("KhoaHoc_SinhVien");

                    b.Navigation("SupportKhoaHoc");
                });

            modelBuilder.Entity("ClbTinhoc.Web.Models.SinhVien", b =>
                {
                    b.Navigation("KhoaHoc_SinhVien");
                });
#pragma warning restore 612, 618
        }
    }
}
